// Header data for every module-card across all pathways.
// Extracted from the previously hand-duplicated <div class="module-header">
// blocks so the shell (icon/title/tag/toggle) has one source of truth.
const MODULE_CARDS = [
  { id: "pw-def", isDoor: false, icon: "<svg class=\"module-icon\" viewBox=\"0 0 28 28\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"1.6\" stroke-linecap=\"round\" stroke-linejoin=\"round\" style=\"width:24px;height:24px;background:transparent;border:none;color:var(--forest-deep);\"><path d=\"M14 24v-8\"/><path d=\"M6 17c0-5 3.5-9 8-11 4.5 2 8 6 8 11\"/><path d=\"M10 24h8\"/></svg>", titleKey: "pwhat.def.title", titleText: "A plain definition", tagKey: "pwhat.def.tag", tagText: "What it is" },
  { id: "pw-vs", isDoor: false, icon: "<svg class=\"module-icon\" viewBox=\"0 0 28 28\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"1.6\" stroke-linecap=\"round\" stroke-linejoin=\"round\" style=\"width:24px;height:24px;background:transparent;border:none;color:var(--forest-deep);\"><circle cx=\"12\" cy=\"12\" r=\"7\"/><path d=\"M17.5 17.5l5.5 5.5\"/></svg>", titleKey: "pwhat.vs.title", titleText: "FBT vs. forest bathing", tagKey: "pwhat.vs.tag", tagText: "Often confused" },
  { id: "pw-works", isDoor: false, icon: "<svg class=\"module-icon\" viewBox=\"0 0 28 28\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"1.6\" stroke-linecap=\"round\" stroke-linejoin=\"round\" style=\"width:24px;height:24px;background:transparent;border:none;color:var(--forest-deep);\"><path d=\"M3 24h22\"/><rect x=\"5\" y=\"15\" width=\"4\" height=\"9\" rx=\"1\"/><rect x=\"12\" y=\"9\" width=\"4\" height=\"15\" rx=\"1\"/><rect x=\"19\" y=\"5\" width=\"4\" height=\"19\" rx=\"1\"/></svg>", titleKey: "pwhat.works.title", titleText: "What the research suggests", tagKey: "pwhat.works.tag", tagText: "In plain terms" },
  { id: "pb-share", isDoor: false, icon: "<svg class=\"module-icon\" viewBox=\"0 0 28 28\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"1.6\" stroke-linecap=\"round\" stroke-linejoin=\"round\" style=\"width:24px;height:24px;background:transparent;border:none;color:var(--forest-deep);\"><path d=\"M5 6a2 2 0 0 1 2-2h14a2 2 0 0 1 2 2v10a2 2 0 0 1-2 2H9.5L5 22V6z\"/><path d=\"M10 11h8M10 15h5\"/></svg>", titleKey: "pbefore.share.title", titleText: "What to share with your practitioner", tagKey: "pbefore.share.tag", tagText: "Practical information" },
  { id: "pb-normal", isDoor: false, icon: "<svg class=\"module-icon\" viewBox=\"0 0 28 28\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"1.6\" stroke-linecap=\"round\" stroke-linejoin=\"round\" style=\"width:24px;height:24px;background:transparent;border:none;color:var(--forest-deep);\"><path d=\"M3 15h5l3-7 5 14 3-7h6\"/></svg>", titleKey: "pbefore.normal.title", titleText: "What's normal to feel", tagKey: "pbefore.normal.tag", tagText: "In the first sessions" },
  { id: "pb-signs", isDoor: false, icon: "<svg class=\"module-icon\" viewBox=\"0 0 28 28\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"1.6\" stroke-linecap=\"round\" stroke-linejoin=\"round\" style=\"width:24px;height:24px;background:transparent;border:none;color:var(--forest-deep);\"><path d=\"M14 23v-9\"/><path d=\"M14 14C13 9 8 6 4 5c0 5 3 9 10 9z\"/><path d=\"M14 14c1-5 6-8 10-9 0 5-3 9-10 9z\"/></svg>", titleKey: "pbefore.signs.title", titleText: "Signs it may be helping", tagKey: "pbefore.signs.tag", tagText: "What to watch for" },
  { id: "pb-bring-back", isDoor: false, icon: "<svg class=\"module-icon\" viewBox=\"0 0 28 28\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"1.6\" stroke-linecap=\"round\" stroke-linejoin=\"round\" style=\"width:24px;height:24px;background:transparent;border:none;color:var(--forest-deep);\"><path d=\"M9 14l-5-5 5-5\"/><path d=\"M4 9h14a6 6 0 0 1 0 12h-4\"/></svg>", titleKey: "pbefore.bb.title", titleText: "Things to bring back to your practitioner", tagKey: "pbefore.bb.tag", tagText: "Between sessions" },
  { id: "pb-questions", isDoor: false, icon: "<svg class=\"module-icon\" viewBox=\"0 0 28 28\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"1.6\" stroke-linecap=\"round\" stroke-linejoin=\"round\" style=\"width:24px;height:24px;background:transparent;border:none;color:var(--forest-deep);\"><circle cx=\"14\" cy=\"14\" r=\"10\"/><path d=\"M11 11a3 3 0 0 1 6 0c0 2.5-3 3.5-3 5.5\"/><circle cx=\"14\" cy=\"20\" r=\"0.8\" fill=\"currentColor\" stroke=\"none\"/></svg>", titleKey: "pbefore.q.title", titleText: "Questions you can ask at a first meeting", tagKey: "pbefore.q.tag", tagText: "Eight starting points" },
  { id: "mod-indications", isDoor: false, icon: "<svg class=\"module-icon\" viewBox=\"0 0 28 28\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"1.6\" stroke-linecap=\"round\" stroke-linejoin=\"round\" style=\"width:24px;height:24px;background:transparent;border:none;color:var(--forest-deep);\"><circle cx=\"14\" cy=\"14\" r=\"10\"/><circle cx=\"14\" cy=\"14\" r=\"6\"/><circle cx=\"14\" cy=\"14\" r=\"2\" fill=\"currentColor\" stroke=\"none\"/></svg>", titleKey: "ref.ind.title", titleText: "Clinical indications", tagKey: "ref.ind.tag", tagText: "Three tiers \u00b7 evidence level \u00b7 recommended format" },
  { id: "mod-contraindications", isDoor: false, icon: "<svg class=\"module-icon\" viewBox=\"0 0 28 28\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"1.6\" stroke-linecap=\"round\" stroke-linejoin=\"round\" style=\"width:24px;height:24px;background:transparent;border:none;color:var(--forest-deep);\"><path d=\"M14 4l11 20H3L14 4z\"/><path d=\"M14 12v6\"/><circle cx=\"14\" cy=\"21\" r=\"0.8\" fill=\"currentColor\" stroke=\"none\"/></svg>", titleKey: "ref.con.title", titleText: "Contraindications", tagKey: "ref.con.tag", tagText: "Absolute \u00b7 relative \u00b7 competency-based" },
  { id: "mod-populations", isDoor: false, icon: "<svg class=\"module-icon\" viewBox=\"0 0 28 28\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"1.6\" stroke-linecap=\"round\" stroke-linejoin=\"round\" style=\"width:24px;height:24px;background:transparent;border:none;color:var(--forest-deep);\"><circle cx=\"10\" cy=\"9\" r=\"4\"/><path d=\"M4 24c0-4.5 2.5-7 6-7s6 2.5 6 7\"/><circle cx=\"21\" cy=\"9\" r=\"3\"/><path d=\"M18 24c0-3 1.5-5.5 3-6.5\"/></svg>", titleKey: "ref.pop.title", titleText: "Population-specific guidance", tagKey: "ref.pop.tag", tagText: "Developmental \u00b7 situational \u00b7 systemic" },
  { id: "mod-dosage", isDoor: false, icon: "<svg class=\"module-icon\" viewBox=\"0 0 28 28\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"1.6\" stroke-linecap=\"round\" stroke-linejoin=\"round\" style=\"width:24px;height:24px;background:transparent;border:none;color:var(--forest-deep);\"><path d=\"M3 24h22\"/><rect x=\"5\" y=\"15\" width=\"4\" height=\"9\" rx=\"1\"/><rect x=\"12\" y=\"9\" width=\"4\" height=\"15\" rx=\"1\"/><rect x=\"19\" y=\"5\" width=\"4\" height=\"19\" rx=\"1\"/></svg>", titleKey: "ref.dos.title", titleText: "Session dosage reference", tagKey: "ref.dos.tag", tagText: "Starting points \u00b7 not protocols" },
  { id: "mod-integration", isDoor: false, icon: "<svg class=\"module-icon\" viewBox=\"0 0 28 28\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"1.6\" stroke-linecap=\"round\" stroke-linejoin=\"round\" style=\"width:24px;height:24px;background:transparent;border:none;color:var(--forest-deep);\"><circle cx=\"10\" cy=\"14\" r=\"6\"/><circle cx=\"18\" cy=\"14\" r=\"6\"/></svg>", titleKey: "ref.int.title", titleText: "Integration with other modalities", tagKey: "ref.int.tag", tagText: "Theoretical connection \u00b7 in practice \u00b7 pocket-guide pairings" },
  { id: "mod-what", isDoor: false, icon: "<svg class=\"module-icon\" viewBox=\"0 0 28 28\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"1.6\" stroke-linecap=\"round\" stroke-linejoin=\"round\" style=\"width:24px;height:24px;background:transparent;border:none;color:var(--forest-deep);\"><path d=\"M14 24v-8\"/><path d=\"M6 17c0-5 3.5-9 8-11 4.5 2 8 6 8 11\"/><path d=\"M10 24h8\"/></svg>", titleKey: "mod.what.title", titleText: "What is FBT?", tagKey: "mod.what.tag", tagText: "Foundations" },
  { id: "mod-evidence", isDoor: false, icon: "<svg class=\"module-icon\" viewBox=\"0 0 28 28\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"1.6\" stroke-linecap=\"round\" stroke-linejoin=\"round\" style=\"width:24px;height:24px;background:transparent;border:none;color:var(--forest-deep);\"><path d=\"M3 24h22\"/><rect x=\"5\" y=\"15\" width=\"4\" height=\"9\" rx=\"1\"/><rect x=\"12\" y=\"9\" width=\"4\" height=\"15\" rx=\"1\"/><rect x=\"19\" y=\"5\" width=\"4\" height=\"19\" rx=\"1\"/></svg>", titleKey: "mod.evidence.title", titleText: "Evidence Base", tagKey: "mod.evidence.tag", tagText: "Research \u00b7 F4Y Findings" },
  { id: "mod-contra", isDoor: false, icon: "<svg class=\"module-icon\" viewBox=\"0 0 28 28\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"1.6\" stroke-linecap=\"round\" stroke-linejoin=\"round\" style=\"width:24px;height:24px;background:transparent;border:none;color:var(--forest-deep);\"><path d=\"M14 4l11 20H3L14 4z\"/><path d=\"M14 12v6\"/><circle cx=\"14\" cy=\"21\" r=\"0.8\" fill=\"currentColor\" stroke=\"none\"/></svg>", titleKey: "mod.contra.title", titleText: "Contraindications", tagKey: "mod.contra.tag", tagText: "Safety & Ethics" },
  { id: "mod-pocket", isDoor: true, screen: "implement", icon: "<svg class=\"module-icon\" viewBox=\"0 0 28 28\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"1.6\" stroke-linecap=\"round\" stroke-linejoin=\"round\" style=\"width:24px;height:24px;background:transparent;border:none;color:var(--forest-deep);\">\n              <path d=\"M6 5h13a3 3 0 0 1 3 3v15a2 2 0 0 1-2 2H8a2 2 0 0 1-2-2V5z\"/>\n              <path d=\"M6 5v18\"/>\n              <path d=\"M10 10h8M10 14h8M10 18h5\"/>\n            </svg>", titleKey: "mod.pocket.title", titleText: "Pocketbook of Activities", tagKey: "mod.pocket.tag", tagText: "5 thematic groups \u00b7 session builder \u00b7 run mode" },
  { id: "mod-adapt", isDoor: true, screen: "implement", icon: "<svg class=\"module-icon\" viewBox=\"0 0 28 28\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"1.6\" stroke-linecap=\"round\" stroke-linejoin=\"round\" style=\"width:24px;height:24px;background:transparent;border:none;color:var(--forest-deep);\">\n              <line x1=\"6\" y1=\"9\" x2=\"22\" y2=\"9\"/>\n              <line x1=\"6\" y1=\"14\" x2=\"22\" y2=\"14\"/>\n              <line x1=\"6\" y1=\"19\" x2=\"22\" y2=\"19\"/>\n              <circle cx=\"11\" cy=\"9\" r=\"2\" fill=\"var(--paper-pure)\"/>\n              <circle cx=\"17\" cy=\"14\" r=\"2\" fill=\"var(--paper-pure)\"/>\n              <circle cx=\"9\" cy=\"19\" r=\"2\" fill=\"var(--paper-pure)\"/>\n            </svg>", titleKey: "mod.adapt.title", titleText: "Adapting Activities", tagKey: "mod.adapt.tag", tagText: "For specific clinical presentations" },
  { id: "mod-pre", isDoor: true, screen: "implement", icon: "<svg class=\"module-icon\" viewBox=\"0 0 28 28\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"1.6\" stroke-linecap=\"round\" stroke-linejoin=\"round\" style=\"width:24px;height:24px;background:transparent;border:none;color:var(--forest-deep);\"><rect x=\"6\" y=\"4\" width=\"13\" height=\"20\" rx=\"2\"/><path d=\"M6 10h13\"/><path d=\"M11 4v6\"/><path d=\"M10 16l2.5 2.5 5-5\"/></svg>", titleKey: "mod.pre.title", titleText: "Pre-Session Checklist", tagKey: "mod.pre.tag", tagText: "Preparation" },
  { id: "mod-plan", isDoor: true, screen: "implement", icon: "<svg class=\"module-icon\" viewBox=\"0 0 28 28\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"1.6\" stroke-linecap=\"round\" stroke-linejoin=\"round\" style=\"width:24px;height:24px;background:transparent;border:none;color:var(--forest-deep);\"><rect x=\"4\" y=\"6\" width=\"20\" height=\"18\" rx=\"2\"/><path d=\"M4 12h20\"/><path d=\"M9 3v6M19 3v6\"/><path d=\"M9 17h2M15 17h2M9 21h2M15 21h2\"/></svg>", titleKey: "mod.plan.title", titleText: "Session Structure Guide", tagKey: "mod.plan.tag", tagText: "60\u201390 min format" },
  { id: "mod-reflect-self", isDoor: true, screen: "reflect", icon: "<svg class=\"module-icon\" viewBox=\"0 0 28 28\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"1.6\" stroke-linecap=\"round\" stroke-linejoin=\"round\" style=\"width:24px;height:24px;background:transparent;border:none;color:var(--forest-deep);\">\n              <circle cx=\"14\" cy=\"10\" r=\"5\"/>\n              <path d=\"M5 24c0-5 4-8 9-8s9 3 9 8\"/>\n              <path d=\"M19 6.5c1 .8 2 2 2 3.5\"/>\n            </svg>", titleKey: "mod.reflectself.title", titleText: "Practitioner Self-Reflection", tagKey: "mod.reflectself.tag", tagText: "Post-session prompts", descText: "Structured questions to examine your own responses, the environment's role, and what to bring to supervision.", badgeText: "4 prompts" },
  { id: "mod-indicators", isDoor: true, screen: "reflect", icon: "<svg class=\"module-icon\" viewBox=\"0 0 28 28\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"1.6\" stroke-linecap=\"round\" stroke-linejoin=\"round\" style=\"width:24px;height:24px;background:transparent;border:none;color:var(--forest-deep);\">\n              <path d=\"M5 20l5-6 4 4 5-8 4 3\"/>\n              <circle cx=\"22\" cy=\"8\" r=\"1.5\" fill=\"currentColor\" stroke=\"none\"/>\n            </svg>", titleKey: "mod.indicators.title", titleText: "Observable Outcome Indicators", tagKey: "mod.indicators.tag", tagText: "What to document", descText: "Non-standardised observational markers to note after each session. Use alongside formal assessment tools.", badgeText: "6 indicators" },
  { id: "mod-glossary", isDoor: true, screen: "reflect", icon: "<svg class=\"module-icon\" viewBox=\"0 0 28 28\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"1.6\" stroke-linecap=\"round\" stroke-linejoin=\"round\" style=\"width:24px;height:24px;background:transparent;border:none;color:var(--forest-deep);\">\n              <path d=\"M6 5h13a3 3 0 0 1 3 3v15a2 2 0 0 1-2 2H8a2 2 0 0 1-2-2V5z\"/>\n              <path d=\"M6 5v18\"/>\n              <path d=\"M10 10h8M10 14h6\"/>\n            </svg>", titleKey: "mod.glossary.title", titleText: "Key Terms", tagKey: "mod.glossary.tag", tagText: "Glossary", descText: "Core concepts from the theoretical foundations of forest-based therapy \u2014 ART, biophilia, phytoncides, and somatic awareness.", badgeText: "4 terms" },
];
